= SNS Service REST API Guide
Naver Campus Hackday - 윤홍찬;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[resources]]
= 리소스

[[resources-board]]
== 게시물

게시물 리소스는 게시물을 만들거나 수정, 삭제 할 때 사용한다.

[[resources-board-create]]
=== 이벤트 생성

`POST` 요청을 사용해서 새 게시물을 만들 수 있다.

operation::create-board[snippets='http-request,request-fields,http-response,response-headers']

[[resources-board-update]]
=== 이벤트 수정

`PUT` 요청을 사용해서 기존 게시물을 수정할 수 있다.

operation::update-board[snippets='http-request,http-response']

[[resources-board-delete]]
=== 이벤트 삭제

`DELETE` 요청을 사용해서 기존 게시물 하나를 삭제할 수 있다.

operation::delete-board[snippets='http-request,http-response']

[[resources-follow]]
== 구독(follow)

구독 리소스는 구독 관계를 설정하거나 조회, 삭제 할 때 사용한다.

[[resources-follow-create]]
=== 구독(follow) 관계 생성

`POST` 요청을 사용해서 구독 관계를 설정 할 수 있다.

operation::create-follow[snippets='http-request,request-fields,http-response']

[[resources-following-get]]
=== 구독하는(following) 유저 조회

`GET` 요청을 사용해서 '특정 유저가' 구독하는 유저들을 조회할 수 있다.

operation::get-following-list[snippets='http-request,path-parameters,request-parameters,http-response']

[[resources-follower-get]]
=== 구독자(follower) 유저 조회

`GET` 요청을 사용해서 '특정 유저를' 구독하는 유저들을 조회할 수 있다.

operation::get-follower-list[snippets='http-request,path-parameters,request-parameters,http-response']

[[resources-follow-delete]]
=== 구독(follow) 관계 삭제

`DELETE` 요청을 사용해서 기존 구독 관계를 삭제할 수 있다.

operation::delete-follow[snippets='http-request,path-parameters,http-response']
